/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}"],
  theme: {
    extend: {
      keyframes: {
        chitchat1: {
          '0%': { content: '"#"' },
          '5%': { content: '"."' },
          '10%': { content: '"^{"' },
          '15%': { content: '"-!"' },
          '20%': { content: '"#$_"' },
          '25%': { content: '"№:0"' },
          '30%': { content: '"#{+."' },
          '35%': { content: '"@}-?"' },
          '40%': { content: '"?{4@%"' },
          '45%': { content: '"=.,^!"' },
          '50%': { content: '"?2@%"' },
          '55%': { content: '"\\;1}]"' },
          '60%': { content: '"?{%:%"', right: '0' },
          '65%': { content: '"|{f[4"', right: '0' },
          '70%': { content: '"{4%0%"', right: '0' },
          '75%': { content: '"\'1_0<"', right: '0' },
          '80%': { content: '"{0%"', right: '0' },
          '85%': { content: '"]>\'"', right: '0' },
          '90%': { content: '"4"', right: '0' },
          '95%': { content: '"2"', right: '0' },
          '100%': { content: '""', right: '0' },
        },
        chitchat2: {
          '0%': { content: '"#"' },
          '10%': { content: '"-!"' },
          '20%': { content: '"^{"' },
          '30%': { content: '"#{+."' },
          '40%': { content: '"№:0"' },
          '50%': { content: '"?2@%"' },
          '60%': { content: '"?2@%"' },
          '70%': { content: '"{4%%"' },
          '80%': { content: '"4"' },
          '90%': { content: '"2"' },
          '100%': { content: '""' },
        },
        chitchat3: {
          '0%': { content: '"#"' },
          '20%': { content: '"$"' },
          '40%': { content: '"*"' },
          '60%': { content: '"@"' },
          '80%': { content: '"3"' },
          '100%': { content: '""' },
        },
        cursorAnimation: {
          '0%': { transform: 'scale(1)' },
          '50%': { transform: 'scale(0.7)' },
          '100%': { transform: 'scale(1)' },
        },
      },
      animation: {
        chitchat1: 'chitchat1 1.2s linear both',
        chitchat2: 'chitchat2 0.7s linear both',
        chitchat3: 'chitchat3 0.5s linear both',
        cursorAnimation: 'cursorAnimation 0.5s alternate',
      },
    },
  },
  plugins: [],
}